# Generated by Django 6.0.3 on 2026-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='upload_date',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['employee'], name='idx_document_employee'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project'], name='idx_document_project'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='idx_document_type'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='idx_document_created_at'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('employee__isnull', False), ('project__isnull', False), _connector='OR'), name='chk_document_owner_required'),
        ),
    ]
