# Generated by Django 6.0.3 on 2026-04-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_remove_document_upload_date_and_more'),
        ('employees', '0003_add_employeesiteassignment_model'),
        ('projects', '0002_convert_site_to_fk'),
        ('sites', '0001_initial_site'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='chk_document_owner_required',
        ),
        migrations.AddField(
            model_name='document',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['site'], name='idx_document_site'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('employee__isnull', False), ('site__isnull', False), ('project__isnull', False), _connector='OR'), name='chk_document_owner_required'),
        ),
    ]
