# Generated by Django 6.0.3 on 2026-04-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('emirate', models.CharField(blank=True, choices=[('Abu Dhabi', 'Abu Dhabi'), ('Dubai', 'Dubai'), ('Sharjah', 'Sharjah'), ('Ajman', 'Ajman'), ('Umm Al Quwain', 'Umm Al Quwain'), ('Ras Al Khaimah', 'Ras Al Khaimah'), ('Fujairah', 'Fujairah')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'site',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_site_status'), models.Index(fields=['emirate'], name='idx_site_emirate'), models.Index(fields=['status', 'emirate'], name='idx_site_status_emirate')],
            },
        ),
    ]
