# Generated by Django 6.0.3 on 2026-04-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_and_more'),
        ('projects', '0003_alter_employeeprojectassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='projects.project'),
        ),
    ]
