# Generated by Django 6.0.3 on 2026-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_idx_employee_status_and_more'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='idx_payroll_employee'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['year', 'month'], name='idx_payroll_year_month'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'year'), name='uq_payroll_employee_month_year'),
        ),
    ]
