# Generated by Django 6.0.3 on 2026-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='idx_employee_status'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['gender'], name='idx_employee_gender'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='idx_employee_position'),
        ),
    ]
