# Generated by Django 6.0.3 on 2026-04-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_idx_employee_status_and_more'),
        ('sites', '0001_initial_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Terminated', 'Terminated')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignments', to='employees.employee')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sites.site')),
            ],
            options={
                'db_table': 'employee_site_assignment',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['status'], name='idx_emp_site_assign_status'), models.Index(fields=['start_date'], name='idx_emp_site_assign_start'), models.Index(fields=['employee', 'status'], name='idx_emp_site_assign_emp_status')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'site', 'start_date'), name='uq_emp_site_assign_emp_site_start')],
            },
        ),
    ]
