# Generated by Django 6.0.3 on 2026-04-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['employee'], name='idx_timesheet_employee'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['project'], name='idx_timesheet_project'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['date'], name='idx_timesheet_date'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('employee', 'project', 'date'), name='uq_timesheet_employee_project_date'),
        ),
    ]
