# Generated by Django 6.0.3 on 2026-04-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_employeesiteassignment_model'),
        ('projects', '0002_convert_site_to_fk'),
        ('sites', '0001_initial_site'),
        ('timesheets', '0002_alter_timesheet_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='sites.site'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['site'], name='idx_timesheet_site'),
        ),
    ]
